server:
  port: 8110 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-edu # 服务名
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_edu?serverTimezone=GMT%2B8
    username: root
    password: 888888
  #返回json的全局时间格式  全局格式
  jackson:
    #设置时区为东八区
    time-zone: GMT+8
    #时间的日期格式
    date-format: yyyy-MM-dd HH:mm:ss
  #spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
    sentinel:
      transport:
        port: 8081 #跟控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: localhost:8080 # 指定控制台服务的地址
  redis:
    host: localhost
    port: 6379
    database: 0
    password:  #默认为空
    lettuce:   # redis数据库连接池
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

feign:
  sentinel:
    enabled: true



#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/online/edu/service/edu/mapper/xml/*.xml


#设置日志的级别  ：FATAL、ERROR、WARN、INFO、DEBUG 设置为error则只能检测前两个到error
#logging:
#  level:
#    root: error

#service-oss: # 调用的提供者的名称
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule   # 负载均衡策略的名称

ribbon:
  MaxAutoRetries: 0 # 同一实例最大重试次数，不包括首次调用，默认0
  MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数，不包括首次所选的server，默认1
  ConnectTimeout: 10000 #连接建立的超时时长，默认1秒
  ReadTimeout: 10000 #处理请求的超时时间，默认为1秒


