server:
  port: 8150 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
  #spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    password:  #默认为空
    lettuce:   # redis数据库连接池
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
  #Mail设置
  #邮箱发件人
  mail:
    host: smtp.qq.com
    username: 1310151064@qq.com
    default-encoding: UTF-8
    password: htsvttwvunosbadb
    properties:
      mail:
        smtp:
          ssl:
            enable: true


#阿里云短信
aliyun:
  sms:
    regionId: xxx
    keyId: xxxx
    keySecret: xxxx
    templateCode: xxx
    signName: xxxx

